=== ONSdigital/dp-data-pipelines/dpypelines/schemas/dataset-ingress/config/v1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "$id": {
            "type": "string"
        },
        "required_files": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "matches": {
                            "type": "string"
                        },
                        "count": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "matches",
                        "count"
                    ]
                }
            ]
        },
        "supplementary_distributions": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "matches": {
                            "type": "string"
                        },
                        "count": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "matches",
                        "count"
                    ]
                }
            ]
        },
        "priority": {
            "type": "string"
        },
        "pipeline": {
            "type": "string"
          },
        "options": {
            "type": "object",
            "properties": {
              "transform_identifier": {
                "type": "string"
              }
            },
            "required": [
              "transform_identifier"
            ]
          }
    },
    "required": [
        "$schema",
        "$id",
        "required_files",
        "supplementary_distributions",
        "priority",
        "pipeline"
    ]
}

=== ONSdigital/dp-data-pipelines/tests/fixtures/test-cases/test_pipeline_config_valid_id.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://raw.githubusercontent.com/ONSdigital/dp-data-pipelines/sandbox/schemas/dataset-ingress/config/v1.json",
    "required_files": [
        {
            "matches": "^data.sdmx$",
            "count": "1"
        }
    ],
    "supplementary_distributions": [
        {
            "matches": "^data.sdmx$",
            "count": "1"
        }
    ],
    "priority": "1",
    "pipeline": "dataset_ingress_v1",
    "options": {
        "transform_identifier": "sdmx.compact.v2.0.prototype.1"
    }
}
